version: "3.9"

services:
  redis:
    container_name: sanic-flash-sale-redis
    image: redis:latest  
    ports:
      - 6379:6379

  postgres:
    container_name: sanic-flash-sale-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password