# This is Configuration of whole project, its content should only include settings of servers.
project:
  name: sanic-flash-sale
  mode: dev
  debug: true

server:
  host: 0.0.0.0
  port: 8000
  worker: 4
  allow_hosts: ['*']

logger:
  default:
    sink: log-{time}.log
    rotation: 50MB
    format: "<r>{time}</r> | {level} | {file} {module} {line} | <g>{message}</g>"
    serialize: true
  stream:
    sink: sys.stdout
    format: "<r>{time}</r> | {level} | {file} {module} {line} | <g>{message}</g>"
    serialize: false

databases:
  default:
    engine: tortoise.backend.postgres.asyncpg
    name: root
    pasword: password
    